name: Deploy static site to EC2 (port 8080)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host *\nStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Upload site
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          EC2_HOST:    ${{ secrets.EC2_HOST }}
          SSH_PORT:    ${{ secrets.SSH_PORT }}
        run: |
          : "${DEPLOY_USER:?Missing DEPLOY_USER}"
          : "${EC2_HOST:?Missing EC2_HOST}"
          : "${SSH_PORT:=22}"
          scp -P "$SSH_PORT" -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r 2139_neural_portfolio/* \
             "$DEPLOY_USER@$EC2_HOST:/tmp/site"

      - name: Publish to Nginx webroot & reload
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          EC2_HOST:    ${{ secrets.EC2_HOST }}
          SSH_PORT:    ${{ secrets.SSH_PORT }}
        run: |
          ssh -p "$SSH_PORT" -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            "$DEPLOY_USER@$EC2_HOST" "\
              sudo rm -rf /var/www/html/* && \
              sudo mv /tmp/site/* /var/www/html/ && \
              sudo chown -R www-data:www-data /var/www/html && \
              sudo systemctl reload nginx \
            "
